spring.application.name=API Gateway


server.port = 2000

eureka.instance.hostname= localhost
eureka.instance.appname= API Gateway

spring.cloud.gateway.mvc.routes[0].id= AdminService
spring.cloud.gateway.mvc.routes[0].uri = http://localhost:2024
spring.cloud.gateway.mvc.routes[0].predicates[0]. = Path=/admin/**


spring.cloud.gateway.mvc.routes[1].id= LoginService
spring.cloud.gateway.mvc.routes[1].uri = http://localhost:2025
spring.cloud.gateway.mvc.routes[1].predicates[0] =Path=/login/**
#
#spring.cloud.gateway.mvc.routes[2].id= course
#spring.cloud.gateway.mvc.routes[2].uri = http://localhost:8083
#spring.cloud.gateway.mvc.routes[2].predicates =Path=/registrations/**


# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoint.info.enabled=true
management.endpoints.web.exposure.include=*